"""Test utilities package for the IP Monitor Bot."""

from .database_cleanup import (
    AsyncDatabaseTestManager,
    DatabaseBackup,
    DatabaseFixtureManager,
    DatabasePerformanceCleanup,
    DatabaseTestManager,
    async_cleanup_test_database,
    async_create_test_database,
    cleanup_test_database,
    create_test_database,
    default_fixture_manager,
    isolated_database_test,
    performance_test_database,
)
from .performance_testing import (
    LoadTestScenario,
    MemoryProfiler,
    PerformanceBenchmark,
    PerformanceMetrics,
    PerformanceTestSuite,
    PerformanceTimer,
    benchmark_cache_performance,
    benchmark_database_performance,
    benchmark_ip_api_performance,
)
from .test_data_generators import (
    APIConfigGenerator,
    APIEndpoint,
    APIResponseGenerator,
    ConfigurationGenerator,
    DatabaseRecordGenerator,
    DiscordDataGenerator,
    IPAddressGenerator,
    IPHistoryGenerator,
    IPRecord,
    MessageQueueDataGenerator,
    TestScenarioGenerator,
)

__all__ = [
    # Performance testing
    "PerformanceMetrics",
    "PerformanceTimer",
    "PerformanceBenchmark",
    "LoadTestScenario",
    "MemoryProfiler",
    "PerformanceTestSuite",
    "benchmark_ip_api_performance",
    "benchmark_database_performance",
    "benchmark_cache_performance",
    # Test data generators
    "IPRecord",
    "APIEndpoint",
    "IPAddressGenerator",
    "IPHistoryGenerator",
    "DiscordDataGenerator",
    "APIResponseGenerator",
    "APIConfigGenerator",
    "DatabaseRecordGenerator",
    "ConfigurationGenerator",
    "MessageQueueDataGenerator",
    "TestScenarioGenerator",
    # Database cleanup
    "DatabaseBackup",
    "DatabaseTestManager",
    "DatabasePerformanceCleanup",
    "DatabaseFixtureManager",
    "AsyncDatabaseTestManager",
    "create_test_database",
    "cleanup_test_database",
    "isolated_database_test",
    "performance_test_database",
    "async_create_test_database",
    "async_cleanup_test_database",
    "default_fixture_manager",
]
